# Generated by Django 4.1.1 on 2022-09-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0002_alter_pets_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_gender',
            field=models.CharField(choices=[('NB', 'Non-Binary'), ('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_owner_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_type',
            field=models.CharField(default='', max_length=120),
        ),
    ]
