# Generated by Django 4.1.1 on 2022-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0005_alter_pets_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_gender',
            field=models.CharField(choices=[('NA', 'Unspecified'), ('NB', 'Non-Binary'), ('M', 'Male'), ('F', 'Female')], default='NA', max_length=2),
        ),
    ]
