# Generated by Django 4.1.1 on 2022-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0006_alter_pets_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_name',
            field=models.CharField(blank=0, default='', max_length=120, null=0),
        ),
    ]
